version: '3'

services:
  web:
    build: .
    command: bash -c "python aviata/manage.py runserver 0.0.0.0:8000"
    container_name: service
    volumes:
      - .:/service
    ports:
      - "8000:8000"
