# Generated by Django 3.0.3 on 2020-02-17 13:14

from django.db import migrations

def popular_routes(apps, schema_editor):
    routes = [
        ('ALA', 'TSE'),
        ('TSE', 'ALA'),
        ('ALA', 'MOW'),
        ('MOW', 'ALA'),
        ('ALA', 'CIT'),
        ('CIT', 'ALA'),
        ('TSE', 'MOW'),
        ('MOW', 'TSE'),
        ('TSE', 'LED'),
        ('LED', 'TSE'),
    ]
    Route = apps.get_model('aviata', 'Route')
    
    for from_code, to_code in routes:
        route = Route()
        route.from_code = from_code
        route.to_code = to_code
        route.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aviata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_routes),
    ]
