# Generated by Django 3.0.3 on 2020-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(max_length=10)),
                ('to_code', models.CharField(max_length=10)),
            ],
        ),
    ]
